name: disaster_management
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  location: ^6.0.1
  flutter_svg: ^2.0.10+1
  flutter_compass: ^0.8.0
  flutter_polyline_points: ^2.0.0
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  zego_uikit_prebuilt_video_conference: ^2.7.4
  url_launcher: ^6.2.6
  weather: ^3.1.1
  bloc: ^8.1.4
  geolocator: ^11.0.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  firebase_storage: ^11.7.3
  firebase_messaging: ^14.9.1
  shared_preferences: ^2.2.3
  # Utility Packages
  http: ^1.1.0
  logger: ^2.0.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  connectivity_plus: ^5.0.1
  change_app_package_name: ^1.1.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1
  image_picker_ios: ^0.8.10+1

  google_fonts: ^6.2.1
  share_plus: ^9.0.0
  flutter_sliding_up_panel: ^2.1.1
  flutter_launcher_icons: ^0.13.1

  # Update Google Play services libraries



  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
     

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
flutter_native_splash:
  color : "#FFFFFF"
  color_dark: "#272727"
  image: "assets/logos/t-store-splash-logo-black.png"
  image_dark: "assets/logos/t-store-splash-logo-white.png"

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: "assets/logos/t-store-splash-logo-black.png"
    image_dark: "assets/logos/t-store-splash-logo-white.png"
  web: false