name: disaster_management
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  location: ^6.0.1
  flutter_svg: ^2.0.10+1
  flutter_compass: ^0.8.0
  flutter_polyline_points: ^2.0.0
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  zego_uikit_prebuilt_video_conference: ^2.7.4
  url_launcher: ^6.2.6
  weather: ^3.1.1
  bloc: ^8.1.4
  geolocator: ^11.0.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  firebase_storage: ^11.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - Assets/Images/